config/routes.rb
Rails.application.routes.draw do
  namespace :journal do
    resources :journals
    resources :submissions
    resources :appointments
    resources :submission_files
    get 'ce' => 'chief_editor_office#index'
    get 'r' => 'reviewer_office#index'
    resources :ce_submissions, only: [:show, :update]
    resources :r_submissions, only: [:show, :update]
  end

resources :profile, only: [:show]
  devise_for :users

  root :to => redirect('/journal/journals')

end

app/models/journal.rb
module Journal
  def self.table_name_prefix
    'journal_'
  end
end

app/models/journal/appointment.rb
class Journal::Appointment < ActiveRecord::Base

  RoleNames = %w[reviewer chief_editor]

  belongs_to :user
  belongs_to :journal

  validates :role_name, presence: true

end

app/models/journal/review.rb
class Journal::Review < ActiveRecord::Base
	include AASM

	Decisions = %w[revise accept reject]

#	validates :decision, :inclusion=> { :in => Decisions }
	validates_inclusion_of :decision, :in => Decisions

	belongs_to :user
	belongs_to :revision

	aasm do
		state :draft, initial: true
		state :cancelled
		state :submitted
		state :nonexistent

		event :sm_update do
			after do |data|
				self.update data
				self.save
			end
			transitions :from => :draft, :to => :draft
		end

		event :sm_submit do
			after do
			end
			transitions :from => :draft, :to => :submitted
		end

		event :sm_cancel do
			after do
			end
			transitions :from => :draft, :to => :cancelled
		end

		event :sm_destroy do
			after do
				self.destroy!
			end
			transitions :to => :nonexistent
		end

	end

end

app/models/journal/submission_file.rb
class Journal::SubmissionFile < ActiveRecord::Base
  belongs_to :revision

#  mount_uploader :file, Journal::SubmissionUploader
#  mount_uploader :file, JournalSubmissionUploader
  mount_uploader :file_data, SubmissionUploader



end

app/controllers/journal/appointments_controller.rb
class Journal::AppointmentsController < Journal::BaseController

#	respond_to :html, :js

	def create
		a_params = appointment_create_params
		user = User.find(a_params[:user_id])
		journal = Journal::Journal.find(a_params[:journal_id])
		role_name = a_params[:role_name]
		a = Journal::Appointment.new({journal: journal, user: user, role_name: role_name})
		if user && journal && journal.owned_or_managed_by?(current_user) && Journal::Appointment::RoleNames.include?(role_name)
			a.save rescue nil
		end
#        respond_with(a, location: profile_path(user))
		redirect_to profile_url(user)
	end

	def destroy
		@appointment = Journal::Appointment.find(params[:id])
		journal = @appointment.journal
		user = @appointment.user
		if user && journal && journal.owned_or_managed_by?(current_user)
			@appointment.destroy
		end
#		respond_with(@appointment) do |format|
#			format.html { redirect_to user }
#		end
#        respond_with(@appointment, location: profile_path(user))
		redirect_to profile_url(user)
	end

private

    def appointment_create_params
      params.require(:journal_appointment).permit(:user_id, :journal_id, :role_name)
    end

end

app/controllers/journal/base_controller.rb
class Journal::BaseController < ApplicationController
#  before_action -> { @section_journal = true }
end

app/controllers/journal/ce_submissions_controller.rb
#class Journal::CeSubmissionsController < Journal::BaseController
class Journal::CeSubmissionsController < Journal::OfficeSubmissionsController
#	before_action -> { @section_journal_journals = true }
	before_action -> { @section_journal_chief_editor_office = true }

#  before_action :set_journal_only, only: [:index, :new]
#  before_action :authenticate_user!

#  respond_to :html, :js

=begin
	def show
		@submission = Journal::Submission.find(params[:id])
		@journal = @submission.journal
		@revision = @submission.last_submitted_revision
		@decision = @revision.revision_decision || @revision.build_revision_decision({user: current_user})
	end
=end

=begin
	def update
		@submission = Journal::Submission.find(params[:id])
		@journal = @submission.journal
		@revision = @submission.last_submitted_revision
#		@decision = @revision.revision_decision || @revision.build_revision_decision({user: current_user})
		@decision = @revision.revision_decision

		data = params[:journal_revision_decision]
		if data
			data = data.permit(:decision, :comment).merge user: current_user
			if @decision
		        @decision.sm_update!(data)
			else
				@revision.sm_create_decision!(data)
				@decision = @revision.revision_decision
			end
		end

		case params[:op]
		when 'submit_decision'
			@decision.sm_submit!
		when 'cancel_decision'
			@decision.sm_cancel!
		when 'add_reviewer_invites'
			r_ids = params[:reviewer_invites]
			r_ids.each do |r_id|
				puts r_id
				u = User.find(r_id)
				#@submission.reviewer_invites.find(user: u)
				inv = @submission.reviewer_invites.build(user: u)
				inv.save! rescue nil
			end if r_ids and r_ids.is_a?(Array)
		when 'activate_reviewer_invite'
			r_id = params[:reviewer_id]
			u = User.find(r_id)
			inv = @submission.reviewer_invites.find_by(user: u)
			inv.sm_activate! if inv.may_sm_activate?
		when 'drop_reviewer_invite'
			r_id = params[:reviewer_id]
			u = User.find(r_id)
			inv = @submission.reviewer_invites.find_by(user: u)
			inv.sm_destroy! if inv.may_sm_destroy?
		end

		@decision.reload if @decision
		@revision.reload
		@submission.reload

		respond_to do |format|
			format.js
		end
	end
=end

private

    def set_journal_only
      #@journal = Journal::Journal.find(params[:journal_id])
    end

end

app/controllers/journal/chief_editor_office_controller.rb
class Journal::ChiefEditorOfficeController < Journal::OfficeController
	before_action -> { @section_journal_chief_editor_office = true }

	def index
		#@journal_submissions = @journal.submissions
		@journal_submissions = @journal.submissions.all_submitted
		respond_with(@journal_submissions)
	end
end

app/controllers/journal/journals_controller.rb
#class Journal::JournalsController < ApplicationController
class Journal::JournalsController < Journal::BaseController

  before_action -> { @section_journal_journals = true }

  before_action :set_journal_journal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  around_action :admin_only, only: [:new, :edit, :create, :update, :destroy]

  respond_to :html, :js

  def index
    @journal_journals = Journal::Journal.all
    respond_with(@journal_journals)
  end

  def show
    respond_with(@journal_journal)
  end

  def new
    @journal_journal = Journal::Journal.new
      respond_with(@journal_journal)
  end

  def edit
    redirect_to action: 'index' unless current_user.is_admin?
  end

  def create
      @journal_journal = Journal::Journal.new(journal_params)
      @journal_journal.user = current_user
      #@journal_journal.save
      flash[:notice] = 'Journal was successfully created.' if @journal_journal.save
      respond_with(@journal_journal)
  end

  def update
      @journal_journal.update(journal_params)
#      @journal_journal.user = current_user
      respond_with(@journal_journal)
  end

  def destroy
      @journal_journal.destroy
      respond_with(@journal_journal)
  end

  private

    def admin_only
      if current_user.is_admin?
        yield
      else
        flash[:error] = 'This operation is for admin only.'
        redirect_to action: 'index'
      end
    end

    def set_journal_journal
      @journal_journal = Journal::Journal.find(params[:id])
    end

#    def journal_journal_params
    def journal_params
      params.require(:journal_journal).permit(:title, :description, :slug, :user_id)
    end
end

app/controllers/journal/office_controller.rb
class Journal::OfficeController < Journal::BaseController
  before_action -> { @section_journal_journals = true }

  before_action :set_journal_only, only: [:index, :new]
  before_action :authenticate_user!

  respond_to :html, :js

private

    def set_journal_only
      @journal = Journal::Journal.find(params[:journal_id])
    end

end

app/controllers/journal/office_submissions_controller.rb
class Journal::OfficeSubmissionsController < Journal::BaseController
	before_action -> { @section_journal_journals = true }
#	before_action -> { @section_journal_chief_editor_office = true }

#  before_action :set_journal_only, only: [:index, :new]
  before_action :authenticate_user!

#  respond_to :html, :js

	def show
		@submission = Journal::Submission.find(params[:id])
		@journal = @submission.journal
		@revision = @submission.last_submitted_revision
		@decision = @revision.revision_decision || @revision.build_revision_decision({user: current_user})
		@my_invite = @submission.user_invite current_user
		@my_review = @revision.user_review(current_user) || @revision.reviews.build(user: current_user)

	end

	def update
		@submission = Journal::Submission.find(params[:id])
		@journal = @submission.journal
		@revision = @submission.last_submitted_revision
#		@decision = @revision.revision_decision || @revision.build_revision_decision({user: current_user})
		@decision = @revision.revision_decision
		@my_invite = @submission.user_invite current_user
		@my_review = @revision.user_review current_user


		data = params[:journal_revision_decision]
		if data
			data = data.permit(:decision, :comment).merge user: current_user
			if @decision
		        @decision.sm_update!(data)
			else
				@revision.sm_create_decision!(data)
				@decision = @revision.revision_decision
			end
		end

		data = params[:journal_review]
		if data
			data = data.permit(:decision, :comment).merge user: current_user
			if @my_review
		        @my_review.sm_update!(data)
			else
				@revision.sm_create_review!(data)
				@my_review = @revision.user_review current_user
			end
		end

		case params[:op]
		when 'submit_decision'
			@decision.sm_submit!
#		when 'cancel_decision'
#			@decision.sm_cancel!
		when 'add_reviewer_invites'
			r_ids = params[:reviewer_invites]
			r_ids.each do |r_id|
				puts r_id
				u = User.find(r_id)
				#@submission.reviewer_invites.find(user: u)
				inv = @submission.reviewer_invites.build(user: u)
				inv.save! rescue nil
			end if r_ids and r_ids.is_a?(Array)
		when 'activate_reviewer_invite'
			r_id = params[:reviewer_id]
			u = User.find(r_id)
			inv = @submission.reviewer_invites.find_by(user: u)
			inv.sm_activate! if inv.may_sm_activate?
		when 'drop_reviewer_invite'
			r_id = params[:reviewer_id]
			u = User.find(r_id)
			inv = @submission.reviewer_invites.find_by(user: u)
			inv.sm_destroy! if inv.may_sm_destroy?
		when 'accept_my_reviewer_invite'
			@my_invite.sm_accept! if @my_invite && @my_invite.may_sm_accept?
		when 'decline_my_reviewer_invite'
			@my_invite.sm_decline! if @my_invite && @my_invite.may_sm_decline?
		when 'submit_my_review'
			@my_review.sm_submit! if @my_review && @my_review.may_sm_submit?
		end

		@decision.reload if @decision
		@revision.reload
		@submission.reload

		@decision = @revision.build_revision_decision({user: current_user}) unless @decision
		@my_review = @revision.reviews.build(user: current_user) unless @my_review


		respond_to do |format|
			format.js
		end
	end


end

app/controllers/journal/r_submissions_controller.rb
#class Journal::RSubmissionsController < Journal::BaseController
class Journal::RSubmissionsController < Journal::OfficeSubmissionsController
#	before_action -> { @section_journal_journals = true }
	before_action -> { @section_journal_reviewer_office = true }

#  before_action :authenticate_user!

#  respond_to :html, :js

=begin
	def show
		@submission = Journal::Submission.find(params[:id])
		@journal = @submission.journal
		@revision = @submission.last_submitted_revision
#		@decision = @revision.revision_decision || @revision.build_revision_decision({user: current_user})
	end
=end

end

app/controllers/journal/reviewer_office_controller.rb
class Journal::ReviewerOfficeController < Journal::OfficeController
	before_action -> { @section_journal_reviewer_office = true }

	def index
		@journal_submissions = @journal.user_reviewer_invites(current_user)
		respond_with(@journal_submissions)
	end
end

app/controllers/journal/submission_files_controller.rb
class Journal::SubmissionFilesController < Journal::BaseController

	def create
		data = params[:journal_submission_file]

		@journal_revision = Journal::Revision.find(data[:revision_id])
		@journal_submission = @journal_revision.submission
		@journal_journal = @journal_submission.journal

		file_type = data[:file_type]
		file = data[:file_data]
		if file
#			@submission_file = Journal::SubmissionFile.new(file_create_params)
#			@submission_file = Journal::SubmissionFile.new(file_create_params)
			#@submission_file = Journal::SubmissionFile.new(file_type: file_type)
			@submission_file = @journal_revision.submission_files.new(file_create_params)
			@submission_file.file_data = file
			flash[:notice] = 'File was successfully uploaded.' if @submission_file.save!
		end
		redirect_to edit_journal_submission_path(@journal_submission)
	end

	def update
		data = params[:journal_submission_file]

		@submission_file = Journal::SubmissionFile.find(params[:id])
		@journal_revision = @submission_file.revision
		@journal_submission = @journal_revision.submission
		@journal_journal = @journal_submission.journal

		file_type = data[:file_type]
		file = data[:file_data]
		if file && @submission_file
#			@submission_file.update
			@submission_file.file_data = file
			flash[:notice] = 'File was successfully uploaded.' if @submission_file.save!
		end
		redirect_to edit_journal_submission_path(@journal_submission)
	end

private

    def file_create_params
      params.require(:journal_submission_file).permit(:file_type)
    end

#    def file_update_params
#      params.require(:journal_submission_file).permit()
#    end

    def set_revision_submission_and_journal
	  @revision = Journal::Revision.find(data[:revision_id])
      @journal_submission = Journal::Submission.find_by(id: params[:id], user: current_user)
      @journal_journal = @journal_submission.journal
    end


end

app/controllers/journal/submissions_controller.rb
#class Journal::SubmissionsController < ApplicationController
class Journal::SubmissionsController < Journal::BaseController

  before_action -> { @section_journal_journals = true }
  before_action -> { @section_journal_submissions = true }


  before_action :set_submission_and_journal, only: [:show, :edit, :update, :destroy]
#  before_action :set_journal_only, only: [:index, :new, :create]
  before_action :set_journal_only, only: [:index, :new]

  before_action :authenticate_user! #, except: [:index, :show]

  #around_action :admin_only, only: [:new, :edit, :create, :update, :destroy]

  respond_to :html, :js

  def index
#    Journal::Submission.destroy_all
    @journal_submissions = current_user.submissions.where(journal: @journal_journal)
#    @journal_submissions = Journal::Submission.all
    respond_with(@journal_submissions)
  end

  def show
    respond_with(@journal_submission)
  end

  def new
    @journal_submission = @journal_journal.submissions.new
    respond_with(@journal_submission)
  end

  def edit
#    @journal_revision = @journal_submission.get_last_created_revision
    @journal_revision = @journal_submission.last_created_revision
    @file_records = @journal_revision ? %w[author_file author_expert_file].map do |type|
      @journal_revision.get_or_new_file_by_type type
    end : []

    puts @file_records.inspect

    #redirect_to action: 'index' unless current_user.is_admin?
  end

  def create
      data = submission_create_params.merge user: current_user
      journal_id = data.delete :journal_id
      @journal_journal = Journal::Journal.find journal_id
      @journal_submission = @journal_journal.submissions.new(data)
      if @journal_submission.save
        flash[:notice] = 'Submission was successfully created.'
        @journal_submission.sm_init!
        respond_with(@journal_submission, location: edit_journal_submission_path(@journal_submission))
      else
        respond_with(@journal_submission)
      end
  end

  def update
#    @journal_revision = @journal_submission.get_last_created_revision
    @journal_revision = @journal_submission.last_created_revision
      data = submission_update_params
      if data
#        @journal_submission.update_draft(data)
        @journal_submission.sm_update!(data)
        @file_records = @journal_revision ? %w[author_file author_expert_file].map do |type|
          @journal_revision.get_or_new_file_by_type type
        end : []
        puts @file_records.inspect
      end

      case params[:op]
      when 'submit'
#        @journal_submission.submit_paper
        @journal_submission.sm_submit! # '1234567'
      when 'revise'
#        @journal_submission.unsubmit_paper
        @journal_submission.sm_revise!
      end

    respond_with(@journal_submission)
  end

  def destroy
#    @journal_submission.destroy_draft
    @journal_submission.sm_destroy!
    respond_with(@journal_submission) do |format|
      format.html { redirect_to journal_submissions_path(journal_id: @journal_journal.id) }
    end
  end

  private

    def set_submission_and_journal
#      @journal_submission = Journal::Submission.find(params[:id])
      @journal_submission = Journal::Submission.find_by(id: params[:id], user: current_user)
      @journal_journal = @journal_submission.journal
    end
    def set_journal_only
      @journal_journal = Journal::Journal.find(params[:journal_id])
    end

    def submission_create_params
      params.require(:journal_submission).permit(:title, :abstract, :journal_id)
    end
    def submission_update_params
#      params[:journal_submission] ? params.require(:journal_submission).permit(:title, :abstract) : nil
      params.require(:journal_submission).permit(:title, :abstract) rescue nil
    end
end

app/views/journal/journals/_form.html.erb
<%= form_for(@journal_journal, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @journal_journal.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@journal_journal.errors.count, "error") %> prohibited this journal_journal from being saved:</h4>

      <ul>
      <% @journal_journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%#= f.label :title, :class => "col-sm-2 control-label" %>
    <%= f.label t('journal.journal_form.title'), :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%#= f.label :description, :class => "col-sm-2 control-label" %>
    <%= f.label t('journal.journal_form.description'), :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :slug, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :slug, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%#= f.submit :class => "btn btn-primary" %>
      <%= f.button :class => "btn btn-success" do %>
        <i class="fa fa-check fa-lg"></i>
        <%= t('journal.journal_form.submit_'+(@journal_journal.persisted? ? 'update' : 'new') ) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/journal/journals/_journal.html.erb
<!--
      <tr>
            <td><%= journal.title %></td>
            <td><%= journal.description %></td>
            <td><%= journal.slug %></td>
            <td><%= journal.user.full_name %></td>
            <td><%= link_to 'Show', journal %></td>
            <% if current_user.is_admin? %>
                <td><%= link_to 'Edit', edit_journal_journal_path(journal) %></td>
                <td><%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' }, rremote: true %></td>
            <% end %>
      </tr>
-->

app/views/journal/journals/edit.html.erb
<div class="page-header">
  <%= link_to journal_journals_path, :class => 'btn btn-default' do %>
    <i class="fa fa-level-up fa-lg"></i>
    <%= t('journal.journals.list_title') %>
  <% end %>
  <%= link_to @journal_journal, :class => 'btn btn-primary' do %>
    <i class="fa fa-info fa-lg"></i>
    <%= t('journal.edit_journal.show_btn') %>
  <% end %>
  <h1><%= t('journal.edit_journal.page_title') %></h1>
</div>

<%= render 'form' %>

app/views/journal/journals/index.html.erb
<div class="page-header">
  <%= link_to new_journal_journal_path, :class => 'btn btn-primary' do %>
    <i class="fa fa-plus fa-lg"></i>
    <%= t('journal.journals.new_journal_btn') %>
  <% end if current_user && current_user.is_admin? %>
  <h1><%= t('journal.journals.list_title') %></h1>
</div>


<div class="list-group">
  <% @journal_journals.each do |journal_journal| %>
    <%= link_to(journal_journal, class: "list-group-item") do %>
      <h4 class="list-group-item-heading"><%= journal_journal.title %></h4>
      <p class="list-group-item-text"><%= journal_journal.description %></p>
    <% end %>
  <% end %>
</div>

app/views/journal/journals/new.html.erb
<div class="page-header">
  <%= link_to journal_journals_path, :class => 'btn btn-default' do %>
    <i class="fa fa-level-up fa-lg"></i>
    <%= t('journal.journals.list_title') %>
  <% end %>
  <h1><%= t('journal.new_journal.page_title') %></h1>
</div>

<%= render 'form' %>

app/views/journal/journals/show.html.erb
<div class="page-header">
  <%= link_to journal_journals_path, :class => 'btn btn-default' do %>
    <i class="fa fa-level-up fa-lg"></i>
    <%= t('journal.journals.list_title') %>
  <% end %>
  <%= link_to edit_journal_journal_path(@journal_journal), :class => 'btn btn-primary' do %>
    <i class="fa fa-edit fa-lg"></i>
    <%= t('journal.show_journal.edit_btn') %>
  <% end if current_user && current_user.is_admin? %>
  <%= link_to @journal_journal, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' do %>
    <i class="fa fa-trash-o fa-lg"></i>
    <%= t('journal.show_journal.destroy_btn') %>
  <% end if current_user && current_user.is_admin? %>


  <!-- h1><%#= t('journal.journal.page_title') %></h1 -->
  <h1><%= @journal_journal.title %></h1>
</div>

<p>
  <%= @journal_journal.description %>
</p>

<div class="panel panel-default">
  <div class="panel-body">
    <!--
    <%#= link_to journal_submissions_path(journal_id: @journal_journal.id), class: 'btn btn-xlg btn-success' do %>
      <i class="fa fa-user"></i><br>
      Author
    <%# end %>
    -->

    <%
      all_roles = [
        {name: 'chief_editor', path: journal_ce_path(journal_id: @journal_journal.id)},
        {name: 'reviewer', path: journal_r_path(journal_id: @journal_journal.id)},
        {name: 'author', path: journal_submissions_path(journal_id: @journal_journal.id)}
      ]
      my_roles = ['author'] | @journal_journal.user_roles(current_user)
    %>

    <% all_roles.each do |role| %>
      <%= link_to role[:path], class: 'btn btn-xlg btn-success' do %>
        <i class="fa fa-user fa-2x"></i><br>
        <%= t('journal.role_name.'+role[:name]) %>
      <% end if my_roles.include?(role[:name]) %>
    <% end %>

  </div>
</div>

<!-- dl class="dl-horizontal">
  <dt><%#= t('journal.journal.title') %>:</dt>
  <dd><%#= @journal_journal.title %></dd>

  <dt><%#= t('journal.journal.description') %>:</dt>
  <dd><%#= @journal_journal.description %></dd>

  <dt><%#= t('journal.journal.slug') %>:</dt>
  <dd><%#= @journal_journal.slug %></dd>

  <dt><%#= t('journal.journal.owner') %>:</dt>
  <dd><%#= @journal_journal.user.full_name %></dd>
</dl -->