config/routes.rb
Rails.application.routes.draw do
  namespace :journal do
    resources :journals
    resources :submissions
    resources :appointments
    resources :submission_files
    get 'ce' => 'chief_editor_office#index'
    get 'r' => 'reviewer_office#index'
    resources :ce_submissions, only: [:show, :update]
    resources :r_submissions, only: [:show, :update]
  end

resources :profile, only: [:show]
  devise_for :users

  root :to => redirect('/journal/journals')

end

app/views/layouts/_breadcrumb.erb
<ol class="breadcrumb">
	<!-- li><a href="/"><%#= t('journal.breadcrumb.root') %></a></li -->

	<% if @section_journal_journals %>
		<li><%= link_to(t('journal.breadcrumb.journals'), journal_journals_path)  %></li>
	<% end %>
	<% if @journal_journal && @journal_journal.persisted? %>
		<li><%= link_to(@journal_journal.title, @journal_journal)  %></li>
		<% if @section_journal_submissions %>
			<li><%= link_to(t('journal.breadcrumb.author_submissions'), journal_submissions_path(journal_id: @journal_journal.id))  %></li>
		<% end %>

		<% if @journal_submission && @journal_submission.persisted? %>
			<li><%= link_to("(%d) " % @journal_submission.id + @journal_submission.title, journal_submission_path(@journal_submission))  %></li>
		<% end %>
	<% end %>

<%#= controller_name %>

	<% if @journal && @journal.persisted? %>
		<li><%= link_to(@journal.title, @journal) %></li>
		<% if @section_journal_chief_editor_office %>
			<li><%= link_to(t('journal.breadcrumb.ce_office_title'), journal_ce_path(journal_id: @journal.id)) %></li>
			<% if @submission && @submission.persisted? %>
				<li><%= link_to("(%d) " % @submission.id + @submission.title, journal_ce_submission_path(@submission))  %></li>
			<% end %>
		<% end %>
		<% if @section_journal_reviewer_office %>
			<li><%= link_to(t('journal.breadcrumb.r_office_title'), journal_r_path(journal_id: @journal.id)) %></li>
			<% if @submission && @submission.persisted? %>
				<li><%= link_to("(%d) " % @submission.id + @submission.title, journal_r_submission_path(@submission))  %></li>
			<% end %>
		<% end %>

	<% end %>


</ol>

app/views/layouts/_nav.html.erb
<nav rrole="navigation" class="navbar nnavbar-custom nnavbar-default navbar-inverse nnavbar-inner navbar-fixed-top">
      <ul class="nav nnavbar-left navbar-nav nnavbar-right">
        <!-- li><a href="/"><i class="fa fa-home"></i> Home</a></li -->
        <li><%= link_to journal_journals_path do %>
        	<!-- i class="fa fa-home"></i> <%#= t('journal.nav.journals') %> -->
        	<i class="fa fa-home fa-lg"></i> <%= t('journal.nav.home') %>
        <% end %></li>
<!-- insert module links before this line -->
<%= render partial: 'layouts/nav_user_links' %>
<!-- insert user links before this line -->
      </ul>
    </nav>

app/views/layouts/_nav_user_links.html.erb
        <% if user_signed_in? %>
          <li><a href="<%= profile_path(current_user) %>"><%= t('journal.nav.my_profile') %>:
            <span>&nbsp;</span><i class="fa fa-user fa-lg fa-fw"></i> <%#= current_user.email %><%= current_user.full_name %></a></li>
          <li><%= link_to(destroy_user_session_path, :method => :delete) do %>
            <i class="fa fa-sign-out fa-lg"></i> <%= t('journal.nav.logout') %>
          <% end %></li>
        <% else %>
          <li><%= link_to(new_user_session_path) do %>
            <i class="fa fa-sign-in fa-lg"></i> <%= t('journal.nav.login') %>
          <% end %></li>
        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Journal Site</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<!-- link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.1/css/material-wfont.css" rel="stylesheet">
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.1/css/ripples.css" rel="stylesheet" -->

<!-- link href="http://bootswatch.com/paper/bootstrap.css" rel="stylesheet" -->
<!-- link href="http://bootswatch.com/cosmo/bootstrap.css" rel="stylesheet" -->
<!-- link href="http://bootswatch.com/yeti/bootstrap.css" rel="stylesheet" -->
<!-- link href="http://bootswatch.com/superhero/bootstrap.css" rel="stylesheet" -->
<!-- link href="http://bootswatch.com/flatly/bootstrap.css" rel="stylesheet" -->

  <%= csrf_meta_tags %>
</head>
<body>
  <header class='clearfix'>
    <%= render partial: 'layouts/nav' -%>
    <%= render partial: 'layouts/breadcrumb' -%>
  </header>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
  <!-- script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.1/js/material.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.2.1/js/ripples.js"></script -->
</body>
</html>